# -*- coding: utf-8 -*-
"""model1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKH6BbUhvj2RtEGiFl6HnXc_qNeaLkpf
"""

!pip install -q --upgrade huggingface_hub gradio

import os

from langchain_community.llms import HuggingFaceHub
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

import gradio as gr
from huggingface_hub import InferenceClient

client = InferenceClient(
    model="meta-llama/Llama-3.1-8B-Instruct",
    token="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"
)

def chat(user_message, history):
    try:
        response = client.chat.completions.create(
            model="meta-llama/Llama-3.1-8B-Instruct",
            messages=[{"role": "user", "content": user_message}],
            max_tokens=200
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error: {str(e)}"

demo = gr.ChatInterface(
    fn=chat,
    title="My AI Chatbot",
    description="Powered by LLaMA 3.1 via HuggingFace",
    examples=["Suggest places to visit in India",
              "Tell me a joke",
              "What is AI?"]
)

demo.launch()